stages:
  ingest:
    cmd: python src/ingestion.py
    deps:
      - src/ingestion.py
      - data/pdfs/
      - src/config.py
    outs:
      - data/chunks.json
    metrics:
      - metrics/ingest_metrics.json


  embed_index:
    cmd: python src/embeddings_store.py
    deps:
      - data/chunks.json
      - src/embeddings_store.py
      - src/config.py
    outs:
      - data/chroma_db/
    metrics:
      - metrics/embed_metrics.json

